export const skillsConfig = [
  {
    category: "Frontend",
    technologies: [
      "React",
      "Next.js",
      "TailwindCSS",
      "SCSS",
      "Headless UI",
      "ShadCN UI",
      "Framer motion",
      "GSAP",
      "Redux",
      "Recoil",
      "Zustand",
      "SWR",
      "Tanstack Query",
      "Tanstack Router",
      "React Hook Form",
      "Jest",
      "Vitest",
      "Cypress",
      "Playwright",
      "Storybook",
    ],
  },
  {
    category: "Javascript runtime",
    technologies: [
      "Node.js",
      "Bun",
      "Deno",
      "Edge runtime (Vercel)",
      "CF Worker",
    ],
  },
  {
    category: "Backend",
    technologies: [
      "Hono.js",
      "Express.js",
      "Fastapi",
      "Flask",
      "Go",
      "Fiber",
      "Mux",
    ],
  },
  {
    category: "Mobile",
    technologies: [
      "React Native",
      "Expo",
      "Flutter",
      "RN MMKV",
      "RN Reanimated",
      "RN Gesture Handler",
      "RN BLE",
      "Flutter BLE",
    ],
  },
  {
    category: "Web3",
    technologies: [
      "Solana",
      "Anchor",
      "Solana Wallet Provider",
      "Solana Mobile Wallet Provider",
      "Ethereum",
      "Web3.js",
    ],
  },
  {
    category: "Firmware",
    technologies: ["C", "C++", "Rust", "Python", "Micropython"],
  },
  {
    category: "Firmware IDE",
    technologies: ["Arduino IDE", "PlatformIO", "ROS"],
  },
  {
    category: "Hardware",
    technologies: [
      "Arduino (UNO, Nano, Micro, Mini)",
      "ESP32",
      "ESP8266",
      "Raspberry Pi Pico",
      "Raspberry Pi (Zero, ZeroW, 3, 4)",
    ],
  },
];
